services:

  mc-proxy:
    image: mc-proxy:latest
    volumes:
      - ./media-controller/proxy/conf/01-set-resolver.envsh:/docker-entrypoint.d/01-set-resolver.envsh:ro
      - ./media-controller/proxy/conf/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./media-controller/proxy/includes:/etc/nginx/includes:ro
      - ./media-controller/proxy/html:/usr/share/nginx/html:ro

  mc-back:
    image: mc-back-dev:latest
    volumes:
      - ./media-controller/back:/app
      - mc_back_node_modules:/app/node_modules

  mc-front:
    image: mc-front-dev:latest
    volumes:
      - ./media-controller/front:/app
      - mc_front_node_modules:/app/node_modules
      - mc_front_angular:/app/.angular

volumes:
  mc_back_node_modules:
  mc_front_node_modules:
  mc_front_angular:
