#config_version=6

bcp:
  debug: True

  connections:
    local_display:
      host: mc-back
      port: 5050
  
  servers:
    url_style:
      ip: 0.0.0.0
      port: 5051
      type: mpf.core.bcp.bcp_socket_client.BCPClientSocket  
