services:

  mc-back:
    image: mc-back:latest
    stdin_open: false
    tty: false

  mc-front:
    image: mc-front-dev:latest
    volumes:
      - ./media-controller/front:/app
      - mc_front_node_modules:/app/node_modules
      - mc_front_angular:/app/.angular

  mc-proxy:
    image: mc-proxy:latest
    depends_on:
      mc-back:
        condition: service_started
      mc-front:
        condition: service_started

volumes:
  mc_front_node_modules:
  mc_front_angular:
