name: mpf-scott-pilgrim

services:
  mc-proxy:
    image: mc-proxy:1.0.0
    container_name: mc-proxy
    ports:
      - "4443:4443/tcp"
      - "8080:8080/tcp"
    networks:
      - mc-front
      - mc-back
    volumes:
      - ../certs/2026:/certs

  mpf:
    image: mpf:0.80
    container_name: mpf
    depends_on:
      - mc-front
      - mc-back
    networks:
      - mc-back
    volumes:
      - ../mpf-config:/mpf
    # Uncomment on the physical machine:
    #devices:
    #  - /dev/cobrapin_board_0
    #  - /dev/cobrapin_board_1

  mc-back:
    image: mc-back:1.0.0
    container_name: mc-back
    networks:
      - mc-back
    volumes:
      - ../mpf-config:/mpf-config

  mc-front:
    image: mc-front:1.0.0
    container_name: mc-front
    networks:
      - mc-front
    volumes:
      - ./media-controller/front/dist:/var/www

networks:
  mc-back:
  mc-front:
