#config_version=5

switches:
  s_trough1:
    number: 1-0-11
  s_trough2:
    number: 1-0-16
  s_trough3:
    number: 1-0-17
  s_trough4:
    number: 1-0-18
  s_plunger:
    number: 0-0-32
  s_start:
    number: 1-0-1
    tags: start
  s_launch:
    number: 1-0-10

  s_left_flipper:
    number: 1-0-2
    tags: left_flipper
  s_right_flipper:
    number: 1-0-3
    tags: right_flipper
  s_left_inlane:
    number: 0-0-34
    tags: playfield_active
  s_right_inlane:
    number: 0-0-35
  s_left_sling:
    number: 1-0-25
  s_right_sling:
    number: 1-0-26
  s_enter_playfield:
    number: 0-0-33
    tags: playfield_active
