
upstream mc_front {
    server mc-front:4200;
}

upstream mc_back {
    server mc-back:5000;
    keepalive 60;
}

upstream dev_tools {
    server localhost:9223;
    keepalive 60;
}

server {
    listen    8080;
    return 301 https://$host$request_uri;
}

server {
    listen 4443 ssl;
    http2 on;
    server_name archpinball.dev;
    ssl_certificate /certs/server.crt;
    ssl_certificate_key /certs/server.key;
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://mc_front;
    }

    location /rdt {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://dev_tools;
    }


    access_log on;
    error_log /var/log/nginx/error.log error;
}

server {
    listen 8443 ssl;
    http2 on;
    server_name archpinball.dev;
    ssl_certificate /certs/server.crt;
    ssl_certificate_key /certs/server.key;
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        include /etc/nginx/includes/wss.conf;
        proxy_pass http://mc_back;

        proxy_read_timeout  36000s;
    }

    access_log on;
    error_log /var/log/nginx/error.log error;
}

server {
    listen 9223;
    http2 on;
    server_name archpinball.dev;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://dev_tools;
    }
}



#server {
#    listen 80;
#    server_name _;
#    root /var/www/html;
#    charset UTF-8;
#    error_page 404 /page-not-found.html;
#    location = /404.html {
#        allow all;
#    }
#    location / {
 #       return 404;
 #   }
 #   access_log off;
 #   log_not_found off;
 #   error_log /var/log/nginx/error.log error;
#}